export const STORAGE_KEY = 'kale_wallet_pubkey';
export const CONTRACT_ADDRESS = 'CDSWUUXGPWDZG76ISK6SUCVPZJMD5YUV66J2FXFXFGDX25XKZJIEITAO';
export const KALE_ISSUER = 'GCHPTWXMT3HYF4RLZHWBNRF4MPXLTJ76ISHMSYIWCCDXWUYOQG5MR2AB';
export const MIN_XLM_BALANCE = 50 * 10000000; // 50 XLM in stroops
export const MINING_DURATION = 1000; // 1 second in milliseconds
