import React from "react";

export const styles: { [key: string]: React.CSSProperties } = {
  container: {
    fontFamily: "Arial, sans-serif",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    minHeight: "100vh",
    margin: 0,
    backgroundColor: "#f0f0f0",
    padding: "10px",
  },
  card: {
    backgroundColor: "white",
    padding: "40px",
    borderRadius: "10px",
    boxShadow: "0 2px 10px rgba(0,0,0,0.1)",
    maxWidth: "500px",
    width: "90%",
  },
  titleRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "30px",
  },
  testnetBadge: {
    backgroundColor: "#3d980cff",
    color: "white",
    padding: "4px 10px",
    borderRadius: "4px",
    fontSize: "14px",
    fontWeight: "bold",
    boxShadow: "0 1px 3px rgba(0,0,0,0.2)",
    textTransform: "uppercase",
  },
  unifiedContainer: {
    textAlign: "left",
  },
  contractRow: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    fontSize: "16px",

    borderRadius: "5px",
    marginBottom: "20px",
    flexWrap: "wrap",
  },
  contractLabel: {
    color: "#666",
    fontWeight: "bold",
  },
  contractHash: {
    color: "#333",
    fontFamily: "monospace",
    wordBreak: "break-all",
    flex: 1,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  accountRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "12px",
    padding: "8px 0",
    flexWrap: "wrap",
  },
  accountInfo: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    flex: 1,
    flexWrap: "wrap",
    minWidth: "0",
  },
  logoutButton: {
    backgroundColor: "#f44336",
    color: "white",
    border: "none",
    padding: "6px 16px",
    fontSize: "16px",
    borderRadius: "4px",
    cursor: "pointer",
    fontWeight: "bold",
    flexShrink: 0,
  },
  connectButton: {
    backgroundColor: "#3498db",
    color: "white",
    border: "none",
    padding: "16px",
    fontSize: "16px",
    borderRadius: "4px",
    cursor: "pointer",
    fontWeight: "bold",
    width: "100%",
    flexShrink: 0,
  },
  errorBanner: {
    backgroundColor: "#ffebee",
    color: "#c62828",
    padding: "8px 12px",
    borderRadius: "4px",
    fontSize: "13px",
    marginTop: "8px",
    marginBottom: "8px",
  },
  label: {
    color: "#666",
    fontSize: "16px",
    fontWeight: "bold",
  },
  value: {
    color: "#333",
    fontSize: "16px",
    fontFamily: "monospace",
    wordBreak: "break-all",
    flex: 1,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  actionSection: {
    marginTop: "25px",
    padding: "20px",
    backgroundColor: "#f8f9fa",
    borderRadius: "8px",
    border: "1px solid #e0e0e0",
  },
  sectionTitle: {
    color: "#333",
    fontSize: "18px",
    marginTop: 0,
    marginBottom: "12px",
    fontWeight: "bold",
  },
  statusMessage: {
    color: "#4CAF50",
    fontSize: "14px",
    marginBottom: "12px",
    padding: "8px",
    backgroundColor: "#e8f5e9",
    borderRadius: "4px",
  },
  title: {
    color: "#333",
    fontSize: "24px",
    margin: 0,
  },
  statusContainer: {
    textAlign: "center",
  },
  spinner: {
    border: "4px solid #f3f3f3",
    borderTop: "4px solid #3498db",
    borderRadius: "50%",
    width: "50px",
    height: "50px",
    animation: "spin 1s linear infinite",
    margin: "0 auto 20px",
  },
  successIcon: {
    color: "#4CAF50",
    fontSize: "60px",
    marginBottom: "20px",
  },
  errorIcon: {
    color: "#f44336",
    fontSize: "60px",
    marginBottom: "20px",
  },
  message: {
    color: "#666",
    fontSize: "18px",
    marginBottom: "10px",
  },
  successMessage: {
    color: "#4CAF50",
    fontSize: "20px",
    fontWeight: "bold",
    marginBottom: "15px",
  },
  errorMessage: {
    color: "#f44336",
    fontSize: "20px",
    fontWeight: "bold",
    marginBottom: "15px",
  },
  publicKey: {
    color: "#333",
    fontSize: "14px",
    fontFamily: "monospace",
    backgroundColor: "#f5f5f5",
    padding: "10px",
    borderRadius: "5px",
    wordBreak: "break-all",
    marginBottom: "15px",
  },
  error: {
    color: "#666",
    fontSize: "14px",
    marginBottom: "15px",
  },
  hint: {
    color: "#999",
    fontSize: "14px",
  },
  button: {
    backgroundColor: "#3498db",
    color: "white",
    border: "none",
    padding: "12px 24px",
    fontSize: "16px",
    borderRadius: "5px",
    cursor: "pointer",
    marginTop: "10px",
    fontWeight: "bold",
    width: "100%",
  },
  buttonDisabled: {
    backgroundColor: "#ccc",
    cursor: "not-allowed",
    opacity: 0.6,
  },
  harvestButton: {
    marginTop: "8px",
    backgroundColor: "#4CAF50",
  },
  errorContainer: {
    width: "100%",
  },
  trustlineHelp: {
    backgroundColor: "#f8f9fa",
    padding: "20px",
    borderRadius: "5px",
    marginTop: "15px",
    textAlign: "left",
  },
  helpTitle: {
    color: "#333",
    fontSize: "16px",
    fontWeight: "bold",
    marginBottom: "10px",
  },
  helpList: {
    color: "#666",
    fontSize: "14px",
    lineHeight: "1.8",
    paddingLeft: "20px",
  },
  code: {
    backgroundColor: "#e9ecef",
    padding: "2px 6px",
    borderRadius: "3px",
    fontFamily: "monospace",
    fontSize: "12px",
    wordBreak: "break-all",
  },
  link: {
    color: "#3498db",
    textDecoration: "none",
  },
};
